# Generated by Django 4.2.7 on 2023-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_author_delete_libro_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
    ]
