# Generated by Django 4.2.7 on 2023-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_editorial_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, to='biblioteca.author'),
        ),
    ]
