# Generated by Django 4.2.7 on 2023-11-28 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(blank=True, to='biblioteca.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
