# Generated by Django 4.2.7 on 2023-12-15 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_libro_autor_alter_libro_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
    ]
