# Generated by Django 4.2.7 on 2023-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_libro_rating_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=10),
        ),
    ]
