# Generated by Django 4.2.7 on 2023-12-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_alter_libro_rating_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='biblioteca.valoracion'),
        ),
    ]
