# Generated by Django 4.2.7 on 2023-12-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0017_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='rating',
        ),
    ]
